### ISSUE TITLE
Illegal string offset

### ISSUE THREAD

**Issue by kaleidografik** [nickforddesign/acf-swatch#12]
Hi, love the plugin.

I'm receiving the following error when returning a value form a colour swatch field:
Warning: Illegal string offset 'value' in /app/public/wp-content/plugins/acf-swatch-master/acf-swatch-v5.php on line 394

Is it possible to help debug?

Thanks.

**Comment by nickforddesign** [comment]
Thank you for reporting this. That makes sense, I'll see what I can do

**Comment by nickforddesign** [comment]
I believe I've fixed the issue, would you mind testing it out (install via the git repository, master branch)? You should be able to return the value without issue now.

**Comment by kaleidografik** [comment]
Hi Nick. Plugin updated and the error being printed on the page has disappeared, however the error still appears in the DOM.

**Comment by nickforddesign** [comment]
Could you elaborate about the DOM issue? Is there a javascript error? Or something is not rendering properly? Thanks!

**Comment by mb79** [comment]
Hi Nick, great addon to ACF ! Same error for me when I don't choose to return result as an array. I see you fixed the problem on your GitHub repo but I'm using composer... Could you update your wpackagist repo please ? Thanks

**Comment by kaleidografik** [comment]
Hey @nickforddesign - This still seems to be an issue, and in fact the plugin seems to only return the 'value', regardless of wether the return is set to be 'value', 'label' or 'both'. Do you have any suggestions of why this might be? Thanks.

**Comment by nickforddesign** [comment]
@kaleidografik did you install the plugin via the repo or composer? i haven't touched this project in quite a while, happy to try to fix it though

**Comment by kaleidografik** [comment]
Thank you Nick, much appreciated! Seems to be working OK now after er-installing form the master repo. Surely this is an in-demand feature that should be rolled into ACF Pro core? I wonder if they’d be interested in your extension? Thank again.
---

 <http://kaleidografik.com/>
Pete Dungey
Digital Director
+44 (0)117 329 0708
Tobacco Factory
Raleigh Road, Bristol BS3 1TF
Twitter <http://twitter.com/kaleidografik> Instagram <http://instagram.com/kaleidografik>
kaleidografik.com

 <http://kaleidografik.com/>
Kaleido Grafik Limited. Company No. 08971848
Registered in England and Wales. VAT No. 255 8204 02

**Comment by mb79** [comment]
> @mb79 sorry it took a while, i pushed the newest release to packagist so you should be fine to use with composer, let me know https://packagist.org/packages/nickford/acf-swatch

Thank you ! It's resolve in this Github repo and in the packagist repo https://packagist.org/packages/nickford/acf-swatch.

At the beginning, I found your plugin here : https://wordpress.org/plugins/acf-color-swatches/
As I usually do, I've search `acf-color-swatches` on wpackagist and I found this : https://wpackagist.org/search?q=acf-color-swatches&type=any&search=
And here is the issue, this two repos are not up to date (typo on tag version 2.0.6). That's why some users still have this issue even if you solve it in your Github repo.

One last thing, the plugin directory are not the same : `acf-color-swatches`in wordpress.org and wpackagist and `acf-swatch` in packagist

**Comment by nickforddev** [comment]
@kaleidografik @mb79 Thank you for those details, that was really helpful.

I just set up an integration to make deploying to the Wordpress plugins store much easier, the 1.0.7 release is pending there right now. I have no idea what the 2.0.6 release was about, probably I messed up when I was trying to figure out how SVN works so I could publish to the plugins store.

Thank you both for your feedback and patience on this issue!
